//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCRGUniversityApp.NEPService.MyEducationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedMyEducation", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedMyEducation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityApp.NEPService.MyEducationService.MyEducationDetail[] myeducationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityApp.NEPService.MyEducationService.MyEducationDetail[] myeducation {
            get {
                return this.myeducationField;
            }
            set {
                if ((object.ReferenceEquals(this.myeducationField, value) != true)) {
                    this.myeducationField = value;
                    this.RaisePropertyChanged("myeducation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyEducationDetail", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class MyEducationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowRevisitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CertificatePrintedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CourseCompletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CredentialIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPassedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalModuleCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int percentCompletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowRevisit {
            get {
                return this.AllowRevisitField;
            }
            set {
                if ((this.AllowRevisitField.Equals(value) != true)) {
                    this.AllowRevisitField = value;
                    this.RaisePropertyChanged("AllowRevisit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CertificatePrinted {
            get {
                return this.CertificatePrintedField;
            }
            set {
                if ((this.CertificatePrintedField.Equals(value) != true)) {
                    this.CertificatePrintedField = value;
                    this.RaisePropertyChanged("CertificatePrinted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateURL {
            get {
                return this.CertificateURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateURLField, value) != true)) {
                    this.CertificateURLField = value;
                    this.RaisePropertyChanged("CertificateURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CourseCompletedDate {
            get {
                return this.CourseCompletedDateField;
            }
            set {
                if ((this.CourseCompletedDateField.Equals(value) != true)) {
                    this.CourseCompletedDateField = value;
                    this.RaisePropertyChanged("CourseCompletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseFile {
            get {
                return this.CourseFileField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseFileField, value) != true)) {
                    this.CourseFileField = value;
                    this.RaisePropertyChanged("CourseFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CredentialID {
            get {
                return this.CredentialIDField;
            }
            set {
                if ((this.CredentialIDField.Equals(value) != true)) {
                    this.CredentialIDField = value;
                    this.RaisePropertyChanged("CredentialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationID {
            get {
                return this.EducationIDField;
            }
            set {
                if ((this.EducationIDField.Equals(value) != true)) {
                    this.EducationIDField = value;
                    this.RaisePropertyChanged("EducationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationTypeID {
            get {
                return this.EducationTypeIDField;
            }
            set {
                if ((this.EducationTypeIDField.Equals(value) != true)) {
                    this.EducationTypeIDField = value;
                    this.RaisePropertyChanged("EducationTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Expired {
            get {
                return this.ExpiredField;
            }
            set {
                if ((this.ExpiredField.Equals(value) != true)) {
                    this.ExpiredField = value;
                    this.RaisePropertyChanged("Expired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPassed {
            get {
                return this.IsPassedField;
            }
            set {
                if ((this.IsPassedField.Equals(value) != true)) {
                    this.IsPassedField = value;
                    this.RaisePropertyChanged("IsPassed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((this.MEIDField.Equals(value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalModule {
            get {
                return this.TotalModuleField;
            }
            set {
                if ((this.TotalModuleField.Equals(value) != true)) {
                    this.TotalModuleField = value;
                    this.RaisePropertyChanged("TotalModule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalModuleCompleted {
            get {
                return this.TotalModuleCompletedField;
            }
            set {
                if ((this.TotalModuleCompletedField.Equals(value) != true)) {
                    this.TotalModuleCompletedField = value;
                    this.RaisePropertyChanged("TotalModuleCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int percentCompleted {
            get {
                return this.percentCompletedField;
            }
            set {
                if ((this.percentCompletedField.Equals(value) != true)) {
                    this.percentCompletedField = value;
                    this.RaisePropertyChanged("percentCompleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedMyEducationAccountHistory", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedMyEducationAccountHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityApp.NEPService.MyEducationService.MyEducationAccountHistory[] accountHistoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityApp.NEPService.MyEducationService.MyEducationAccountHistory[] accountHistory {
            get {
                return this.accountHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.accountHistoryField, value) != true)) {
                    this.accountHistoryField = value;
                    this.RaisePropertyChanged("accountHistory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyEducationAccountHistory", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class MyEducationAccountHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserAllAccessPassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedDate {
            get {
                return this.CompletedDateField;
            }
            set {
                if ((this.CompletedDateField.Equals(value) != true)) {
                    this.CompletedDateField = value;
                    this.RaisePropertyChanged("CompletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationID {
            get {
                return this.EducationIDField;
            }
            set {
                if ((this.EducationIDField.Equals(value) != true)) {
                    this.EducationIDField = value;
                    this.RaisePropertyChanged("EducationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((this.MEIDField.Equals(value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentStatusField, value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserAllAccessPassID {
            get {
                return this.UserAllAccessPassIDField;
            }
            set {
                if ((this.UserAllAccessPassIDField.Equals(value) != true)) {
                    this.UserAllAccessPassIDField = value;
                    this.RaisePropertyChanged("UserAllAccessPassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyEducationModuleDetail", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class MyEducationModuleDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationModuleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityApp.NEPService.MyEducationService.EducationModuleFile[] EducationModuleFileDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationModulePositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationModuleTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExpireDaysLeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsTimerRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeLeftField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedDate {
            get {
                return this.CompletedDateField;
            }
            set {
                if ((this.CompletedDateField.Equals(value) != true)) {
                    this.CompletedDateField = value;
                    this.RaisePropertyChanged("CompletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseFile {
            get {
                return this.CourseFileField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseFileField, value) != true)) {
                    this.CourseFileField = value;
                    this.RaisePropertyChanged("CourseFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationID {
            get {
                return this.EducationIDField;
            }
            set {
                if ((this.EducationIDField.Equals(value) != true)) {
                    this.EducationIDField = value;
                    this.RaisePropertyChanged("EducationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationModuleDescription {
            get {
                return this.EducationModuleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationModuleDescriptionField, value) != true)) {
                    this.EducationModuleDescriptionField = value;
                    this.RaisePropertyChanged("EducationModuleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityApp.NEPService.MyEducationService.EducationModuleFile[] EducationModuleFileDetail {
            get {
                return this.EducationModuleFileDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationModuleFileDetailField, value) != true)) {
                    this.EducationModuleFileDetailField = value;
                    this.RaisePropertyChanged("EducationModuleFileDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationModuleID {
            get {
                return this.EducationModuleIDField;
            }
            set {
                if ((this.EducationModuleIDField.Equals(value) != true)) {
                    this.EducationModuleIDField = value;
                    this.RaisePropertyChanged("EducationModuleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationModuleName {
            get {
                return this.EducationModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationModuleNameField, value) != true)) {
                    this.EducationModuleNameField = value;
                    this.RaisePropertyChanged("EducationModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationModulePosition {
            get {
                return this.EducationModulePositionField;
            }
            set {
                if ((this.EducationModulePositionField.Equals(value) != true)) {
                    this.EducationModulePositionField = value;
                    this.RaisePropertyChanged("EducationModulePosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationModuleTime {
            get {
                return this.EducationModuleTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationModuleTimeField, value) != true)) {
                    this.EducationModuleTimeField = value;
                    this.RaisePropertyChanged("EducationModuleTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ExpireDaysLeft {
            get {
                return this.ExpireDaysLeftField;
            }
            set {
                if ((this.ExpireDaysLeftField.Equals(value) != true)) {
                    this.ExpireDaysLeftField = value;
                    this.RaisePropertyChanged("ExpireDaysLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileTypeName {
            get {
                return this.FileTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeNameField, value) != true)) {
                    this.FileTypeNameField = value;
                    this.RaisePropertyChanged("FileTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsTimerRequired {
            get {
                return this.IsTimerRequiredField;
            }
            set {
                if ((this.IsTimerRequiredField.Equals(value) != true)) {
                    this.IsTimerRequiredField = value;
                    this.RaisePropertyChanged("IsTimerRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((this.MEIDField.Equals(value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEMID {
            get {
                return this.MEMIDField;
            }
            set {
                if ((this.MEMIDField.Equals(value) != true)) {
                    this.MEMIDField = value;
                    this.RaisePropertyChanged("MEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleFile {
            get {
                return this.ModuleFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleFileField, value) != true)) {
                    this.ModuleFileField = value;
                    this.RaisePropertyChanged("ModuleFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeLeft {
            get {
                return this.TimeLeftField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeLeftField, value) != true)) {
                    this.TimeLeftField = value;
                    this.RaisePropertyChanged("TimeLeft");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EducationModuleFile", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class EducationModuleFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocumentUploadedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationModuleFileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocumentUploadedDate {
            get {
                return this.DocumentUploadedDateField;
            }
            set {
                if ((this.DocumentUploadedDateField.Equals(value) != true)) {
                    this.DocumentUploadedDateField = value;
                    this.RaisePropertyChanged("DocumentUploadedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationModuleFileID {
            get {
                return this.EducationModuleFileIDField;
            }
            set {
                if ((this.EducationModuleFileIDField.Equals(value) != true)) {
                    this.EducationModuleFileIDField = value;
                    this.RaisePropertyChanged("EducationModuleFileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationModuleID {
            get {
                return this.EducationModuleIDField;
            }
            set {
                if ((this.EducationModuleIDField.Equals(value) != true)) {
                    this.EducationModuleIDField = value;
                    this.RaisePropertyChanged("EducationModuleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileTypeID {
            get {
                return this.FileTypeIDField;
            }
            set {
                if ((this.FileTypeIDField.Equals(value) != true)) {
                    this.FileTypeIDField = value;
                    this.RaisePropertyChanged("FileTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleFile {
            get {
                return this.ModuleFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleFileField, value) != true)) {
                    this.ModuleFileField = value;
                    this.RaisePropertyChanged("ModuleFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyEducationModule", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class MyEducationModule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MEMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeLeftField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedDate {
            get {
                return this.CompletedDateField;
            }
            set {
                if ((this.CompletedDateField.Equals(value) != true)) {
                    this.CompletedDateField = value;
                    this.RaisePropertyChanged("CompletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationModuleID {
            get {
                return this.EducationModuleIDField;
            }
            set {
                if ((this.EducationModuleIDField.Equals(value) != true)) {
                    this.EducationModuleIDField = value;
                    this.RaisePropertyChanged("EducationModuleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEID {
            get {
                return this.MEIDField;
            }
            set {
                if ((this.MEIDField.Equals(value) != true)) {
                    this.MEIDField = value;
                    this.RaisePropertyChanged("MEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MEMID {
            get {
                return this.MEMIDField;
            }
            set {
                if ((this.MEMIDField.Equals(value) != true)) {
                    this.MEMIDField = value;
                    this.RaisePropertyChanged("MEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeLeft {
            get {
                return this.TimeLeftField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeLeftField, value) != true)) {
                    this.TimeLeftField = value;
                    this.RaisePropertyChanged("TimeLeft");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateDetail", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class CertificateDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccreditorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CredentialUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccreditorName {
            get {
                return this.AccreditorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccreditorNameField, value) != true)) {
                    this.AccreditorNameField = value;
                    this.RaisePropertyChanged("AccreditorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateMessage {
            get {
                return this.CertificateMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateMessageField, value) != true)) {
                    this.CertificateMessageField = value;
                    this.RaisePropertyChanged("CertificateMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedDate {
            get {
                return this.CompletedDateField;
            }
            set {
                if ((this.CompletedDateField.Equals(value) != true)) {
                    this.CompletedDateField = value;
                    this.RaisePropertyChanged("CompletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialProgram {
            get {
                return this.CredentialProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialProgramField, value) != true)) {
                    this.CredentialProgramField = value;
                    this.RaisePropertyChanged("CredentialProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CredentialUnit {
            get {
                return this.CredentialUnitField;
            }
            set {
                if ((this.CredentialUnitField.Equals(value) != true)) {
                    this.CredentialUnitField = value;
                    this.RaisePropertyChanged("CredentialUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NEPService.MyEducationService.IMyEducationService")]
    public interface IMyEducationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationCompletedByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationCompletedByUserIDPagedRespon" +
            "se")]
        HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation GetMyEducationCompletedByUserIDPaged(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationCompletedByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationCompletedByUserIDPagedRespon" +
            "se")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation> GetMyEducationCompletedByUserIDPagedAsync(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationInProgressByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationInProgressByUserIDPagedRespo" +
            "nse")]
        HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation GetMyEducationInProgressByUserIDPaged(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationInProgressByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationInProgressByUserIDPagedRespo" +
            "nse")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation> GetMyEducationInProgressByUserIDPagedAsync(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationDetailByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationDetailByUserIDPagedResponse")]
        HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducationAccountHistory GetMyEducationDetailByUserIDPaged(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationDetailByUserIDPaged", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationDetailByUserIDPagedResponse")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducationAccountHistory> GetMyEducationDetailByUserIDPagedAsync(int userID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailsByMEID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailsByMEIDResponse" +
            "")]
        HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail[] GetMyEducationModulesDetailsByMEID(int meID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailsByMEID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailsByMEIDResponse" +
            "")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail[]> GetMyEducationModulesDetailsByMEIDAsync(int meID, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailByMEMID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailByMEMIDResponse" +
            "")]
        HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail GetMyEducationModulesDetailByMEMID(int memID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailByMEMID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationModulesDetailByMEMIDResponse" +
            "")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail> GetMyEducationModulesDetailByMEMIDAsync(int memID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationModule", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleResponse")]
        int UpdateMyEducationModule(HCRGUniversityApp.NEPService.MyEducationService.MyEducationModule myEducationModule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationModule", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleResponse")]
        System.Threading.Tasks.Task<int> UpdateMyEducationModuleAsync(HCRGUniversityApp.NEPService.MyEducationService.MyEducationModule myEducationModule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleTimeLeft", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleTimeLeftResponse")]
        void UpdateMyEducationModuleTimeLeft(int memID, string TimeLeft);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleTimeLeft", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationModuleTimeLeftResponse")]
        System.Threading.Tasks.Task UpdateMyEducationModuleTimeLeftAsync(int memID, string TimeLeft);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationExpiredByUserID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationExpiredByUserIDResponse")]
        void UpdateMyEducationExpiredByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationExpiredByUserID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationExpiredByUserIDResponse")]
        System.Threading.Tasks.Task UpdateMyEducationExpiredByUserIDAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationCourseCompletedByMEMID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationCourseCompletedByMEMIDRes" +
            "ponse")]
        void UpdateMyEducationCourseCompletedByMEMID(int memID, int meID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationCourseCompletedByMEMID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationCourseCompletedByMEMIDRes" +
            "ponse")]
        System.Threading.Tasks.Task UpdateMyEducationCourseCompletedByMEMIDAsync(int memID, int meID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationForCertificateByMEID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationForCertificateByMEIDRespo" +
            "nse")]
        void UpdateMyEducationForCertificateByMEID(int meid, bool isPrinted, string certificateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/UpdateMyEducationForCertificateByMEID", ReplyAction="http://tempuri.org/IMyEducationService/UpdateMyEducationForCertificateByMEIDRespo" +
            "nse")]
        System.Threading.Tasks.Task UpdateMyEducationForCertificateByMEIDAsync(int meid, bool isPrinted, string certificateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetCertificateDetailByMEID", ReplyAction="http://tempuri.org/IMyEducationService/GetCertificateDetailByMEIDResponse")]
        HCRGUniversityApp.NEPService.MyEducationService.CertificateDetail GetCertificateDetailByMEID(int meID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetCertificateDetailByMEID", ReplyAction="http://tempuri.org/IMyEducationService/GetCertificateDetailByMEIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.CertificateDetail> GetCertificateDetailByMEIDAsync(int meID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationByID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationByIDResponse")]
        int GetMyEducationByID(int meID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyEducationService/GetMyEducationByID", ReplyAction="http://tempuri.org/IMyEducationService/GetMyEducationByIDResponse")]
        System.Threading.Tasks.Task<int> GetMyEducationByIDAsync(int meID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyEducationServiceChannel : HCRGUniversityApp.NEPService.MyEducationService.IMyEducationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyEducationServiceClient : System.ServiceModel.ClientBase<HCRGUniversityApp.NEPService.MyEducationService.IMyEducationService>, HCRGUniversityApp.NEPService.MyEducationService.IMyEducationService {
        
        public MyEducationServiceClient() {
        }
        
        public MyEducationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyEducationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEducationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyEducationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation GetMyEducationCompletedByUserIDPaged(int userID, int skip, int take) {
            return base.Channel.GetMyEducationCompletedByUserIDPaged(userID, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation> GetMyEducationCompletedByUserIDPagedAsync(int userID, int skip, int take) {
            return base.Channel.GetMyEducationCompletedByUserIDPagedAsync(userID, skip, take);
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation GetMyEducationInProgressByUserIDPaged(int userID, int skip, int take) {
            return base.Channel.GetMyEducationInProgressByUserIDPaged(userID, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducation> GetMyEducationInProgressByUserIDPagedAsync(int userID, int skip, int take) {
            return base.Channel.GetMyEducationInProgressByUserIDPagedAsync(userID, skip, take);
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducationAccountHistory GetMyEducationDetailByUserIDPaged(int userID, int skip, int take) {
            return base.Channel.GetMyEducationDetailByUserIDPaged(userID, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.PagedMyEducationAccountHistory> GetMyEducationDetailByUserIDPagedAsync(int userID, int skip, int take) {
            return base.Channel.GetMyEducationDetailByUserIDPagedAsync(userID, skip, take);
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail[] GetMyEducationModulesDetailsByMEID(int meID, int userID) {
            return base.Channel.GetMyEducationModulesDetailsByMEID(meID, userID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail[]> GetMyEducationModulesDetailsByMEIDAsync(int meID, int userID) {
            return base.Channel.GetMyEducationModulesDetailsByMEIDAsync(meID, userID);
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail GetMyEducationModulesDetailByMEMID(int memID) {
            return base.Channel.GetMyEducationModulesDetailByMEMID(memID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.MyEducationModuleDetail> GetMyEducationModulesDetailByMEMIDAsync(int memID) {
            return base.Channel.GetMyEducationModulesDetailByMEMIDAsync(memID);
        }
        
        public int UpdateMyEducationModule(HCRGUniversityApp.NEPService.MyEducationService.MyEducationModule myEducationModule) {
            return base.Channel.UpdateMyEducationModule(myEducationModule);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMyEducationModuleAsync(HCRGUniversityApp.NEPService.MyEducationService.MyEducationModule myEducationModule) {
            return base.Channel.UpdateMyEducationModuleAsync(myEducationModule);
        }
        
        public void UpdateMyEducationModuleTimeLeft(int memID, string TimeLeft) {
            base.Channel.UpdateMyEducationModuleTimeLeft(memID, TimeLeft);
        }
        
        public System.Threading.Tasks.Task UpdateMyEducationModuleTimeLeftAsync(int memID, string TimeLeft) {
            return base.Channel.UpdateMyEducationModuleTimeLeftAsync(memID, TimeLeft);
        }
        
        public void UpdateMyEducationExpiredByUserID(int userID) {
            base.Channel.UpdateMyEducationExpiredByUserID(userID);
        }
        
        public System.Threading.Tasks.Task UpdateMyEducationExpiredByUserIDAsync(int userID) {
            return base.Channel.UpdateMyEducationExpiredByUserIDAsync(userID);
        }
        
        public void UpdateMyEducationCourseCompletedByMEMID(int memID, int meID) {
            base.Channel.UpdateMyEducationCourseCompletedByMEMID(memID, meID);
        }
        
        public System.Threading.Tasks.Task UpdateMyEducationCourseCompletedByMEMIDAsync(int memID, int meID) {
            return base.Channel.UpdateMyEducationCourseCompletedByMEMIDAsync(memID, meID);
        }
        
        public void UpdateMyEducationForCertificateByMEID(int meid, bool isPrinted, string certificateName) {
            base.Channel.UpdateMyEducationForCertificateByMEID(meid, isPrinted, certificateName);
        }
        
        public System.Threading.Tasks.Task UpdateMyEducationForCertificateByMEIDAsync(int meid, bool isPrinted, string certificateName) {
            return base.Channel.UpdateMyEducationForCertificateByMEIDAsync(meid, isPrinted, certificateName);
        }
        
        public HCRGUniversityApp.NEPService.MyEducationService.CertificateDetail GetCertificateDetailByMEID(int meID) {
            return base.Channel.GetCertificateDetailByMEID(meID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityApp.NEPService.MyEducationService.CertificateDetail> GetCertificateDetailByMEIDAsync(int meID) {
            return base.Channel.GetCertificateDetailByMEIDAsync(meID);
        }
        
        public int GetMyEducationByID(int meID) {
            return base.Channel.GetMyEducationByID(meID);
        }
        
        public System.Threading.Tasks.Task<int> GetMyEducationByIDAsync(int meID) {
            return base.Channel.GetMyEducationByIDAsync(meID);
        }
    }
}
