//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCRGUniversityMgtApp.NEPService.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductCurrentBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductTotalQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductCurrentBalance {
            get {
                return this.ProductCurrentBalanceField;
            }
            set {
                if ((this.ProductCurrentBalanceField.Equals(value) != true)) {
                    this.ProductCurrentBalanceField = value;
                    this.RaisePropertyChanged("ProductCurrentBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDesc {
            get {
                return this.ProductDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescField, value) != true)) {
                    this.ProductDescField = value;
                    this.RaisePropertyChanged("ProductDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductFile {
            get {
                return this.ProductFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductFileField, value) != true)) {
                    this.ProductFileField = value;
                    this.RaisePropertyChanged("ProductFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductTotalQuantity {
            get {
                return this.ProductTotalQuantityField;
            }
            set {
                if ((this.ProductTotalQuantityField.Equals(value) != true)) {
                    this.ProductTotalQuantityField = value;
                    this.RaisePropertyChanged("ProductTotalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedProduct", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityMgtApp.NEPService.ProductService.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityMgtApp.NEPService.ProductService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedProductPurchase", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedProductPurchase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityMgtApp.NEPService.ProductService.ProductPurchase[] ProductPurchaseDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductPurchase[] ProductPurchaseDetails {
            get {
                return this.ProductPurchaseDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPurchaseDetailsField, value) != true)) {
                    this.ProductPurchaseDetailsField = value;
                    this.RaisePropertyChanged("ProductPurchaseDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductPurchase", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductPurchase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductCurrentBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductShoppingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductTotalQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLastnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductCurrentBalance {
            get {
                return this.ProductCurrentBalanceField;
            }
            set {
                if ((this.ProductCurrentBalanceField.Equals(value) != true)) {
                    this.ProductCurrentBalanceField = value;
                    this.RaisePropertyChanged("ProductCurrentBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDesc {
            get {
                return this.ProductDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescField, value) != true)) {
                    this.ProductDescField = value;
                    this.RaisePropertyChanged("ProductDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductFile {
            get {
                return this.ProductFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductFileField, value) != true)) {
                    this.ProductFileField = value;
                    this.RaisePropertyChanged("ProductFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductShoppingID {
            get {
                return this.ProductShoppingIDField;
            }
            set {
                if ((this.ProductShoppingIDField.Equals(value) != true)) {
                    this.ProductShoppingIDField = value;
                    this.RaisePropertyChanged("ProductShoppingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductTotalQuantity {
            get {
                return this.ProductTotalQuantityField;
            }
            set {
                if ((this.ProductTotalQuantityField.Equals(value) != true)) {
                    this.ProductTotalQuantityField = value;
                    this.RaisePropertyChanged("ProductTotalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingPaymentID {
            get {
                return this.ShippingPaymentIDField;
            }
            set {
                if ((this.ShippingPaymentIDField.Equals(value) != true)) {
                    this.ShippingPaymentIDField = value;
                    this.RaisePropertyChanged("ShippingPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFirstname {
            get {
                return this.UserFirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFirstnameField, value) != true)) {
                    this.UserFirstnameField = value;
                    this.RaisePropertyChanged("UserFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLastname {
            get {
                return this.UserLastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLastnameField, value) != true)) {
                    this.UserLastnameField = value;
                    this.RaisePropertyChanged("UserLastname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductShopping", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductShopping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CoupanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrandtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductShoppingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TaxPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CoupanID {
            get {
                return this.CoupanIDField;
            }
            set {
                if ((this.CoupanIDField.Equals(value) != true)) {
                    this.CoupanIDField = value;
                    this.RaisePropertyChanged("CoupanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Grandtotal {
            get {
                return this.GrandtotalField;
            }
            set {
                if ((this.GrandtotalField.Equals(value) != true)) {
                    this.GrandtotalField = value;
                    this.RaisePropertyChanged("Grandtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductShoppingID {
            get {
                return this.ProductShoppingIDField;
            }
            set {
                if ((this.ProductShoppingIDField.Equals(value) != true)) {
                    this.ProductShoppingIDField = value;
                    this.RaisePropertyChanged("ProductShoppingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingPaymentID {
            get {
                return this.ShippingPaymentIDField;
            }
            set {
                if ((this.ShippingPaymentIDField.Equals(value) != true)) {
                    this.ShippingPaymentIDField = value;
                    this.RaisePropertyChanged("ShippingPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TaxPercentage {
            get {
                return this.TaxPercentageField;
            }
            set {
                if ((this.TaxPercentageField.Equals(value) != true)) {
                    this.TaxPercentageField = value;
                    this.RaisePropertyChanged("TaxPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQuantity", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductQuantity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProdQuantityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductQuantityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdQuantity {
            get {
                return this.ProdQuantityField;
            }
            set {
                if ((this.ProdQuantityField.Equals(value) != true)) {
                    this.ProdQuantityField = value;
                    this.RaisePropertyChanged("ProdQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProdQuantityDate {
            get {
                return this.ProdQuantityDateField;
            }
            set {
                if ((this.ProdQuantityDateField.Equals(value) != true)) {
                    this.ProdQuantityDateField = value;
                    this.RaisePropertyChanged("ProdQuantityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductQuantityID {
            get {
                return this.ProductQuantityIDField;
            }
            set {
                if ((this.ProductQuantityIDField.Equals(value) != true)) {
                    this.ProductQuantityIDField = value;
                    this.RaisePropertyChanged("ProductQuantityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedProductQuantity", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedProductQuantity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity[] ProductQuantityDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity[] ProductQuantityDetails {
            get {
                return this.ProductQuantityDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductQuantityDetailsField, value) != true)) {
                    this.ProductQuantityDetailsField = value;
                    this.RaisePropertyChanged("ProductQuantityDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductShippingDetail", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductShippingDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProductShippedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductShippingDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShippingPaymentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProductShippedOn {
            get {
                return this.ProductShippedOnField;
            }
            set {
                if ((this.ProductShippedOnField.Equals(value) != true)) {
                    this.ProductShippedOnField = value;
                    this.RaisePropertyChanged("ProductShippedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductShippingDetailID {
            get {
                return this.ProductShippingDetailIDField;
            }
            set {
                if ((this.ProductShippingDetailIDField.Equals(value) != true)) {
                    this.ProductShippingDetailIDField = value;
                    this.RaisePropertyChanged("ProductShippingDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingPaymentID {
            get {
                return this.ShippingPaymentIDField;
            }
            set {
                if ((this.ShippingPaymentIDField.Equals(value) != true)) {
                    this.ShippingPaymentIDField = value;
                    this.RaisePropertyChanged("ShippingPaymentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedProductShippingDetail", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedProductShippingDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail[] ProductShippingDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail[] ProductShippingDetails {
            get {
                return this.ProductShippingDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductShippingDetailsField, value) != true)) {
                    this.ProductShippingDetailsField = value;
                    this.RaisePropertyChanged("ProductShippingDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductShippingAddressDetailByID", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductShippingAddressDetailByID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductShoppingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SACityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SALastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SAPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SAStateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductShoppingID {
            get {
                return this.ProductShoppingIDField;
            }
            set {
                if ((this.ProductShoppingIDField.Equals(value) != true)) {
                    this.ProductShoppingIDField = value;
                    this.RaisePropertyChanged("ProductShoppingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAAddress {
            get {
                return this.SAAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SAAddressField, value) != true)) {
                    this.SAAddressField = value;
                    this.RaisePropertyChanged("SAAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAAddress2 {
            get {
                return this.SAAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SAAddress2Field, value) != true)) {
                    this.SAAddress2Field = value;
                    this.RaisePropertyChanged("SAAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SACity {
            get {
                return this.SACityField;
            }
            set {
                if ((object.ReferenceEquals(this.SACityField, value) != true)) {
                    this.SACityField = value;
                    this.RaisePropertyChanged("SACity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAFirstName {
            get {
                return this.SAFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SAFirstNameField, value) != true)) {
                    this.SAFirstNameField = value;
                    this.RaisePropertyChanged("SAFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SALastName {
            get {
                return this.SALastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SALastNameField, value) != true)) {
                    this.SALastNameField = value;
                    this.RaisePropertyChanged("SALastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SAPostalCode {
            get {
                return this.SAPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SAPostalCodeField, value) != true)) {
                    this.SAPostalCodeField = value;
                    this.RaisePropertyChanged("SAPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SAStateID {
            get {
                return this.SAStateIDField;
            }
            set {
                if ((this.SAStateIDField.Equals(value) != true)) {
                    this.SAStateIDField = value;
                    this.RaisePropertyChanged("SAStateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName {
            get {
                return this.StateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StateNameField, value) != true)) {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedProductPurchasesRecord", Namespace="http://schemas.datacontract.org/2004/07/HCRGUniversityService.DTO.Paged")]
    [System.SerializableAttribute()]
    public partial class PagedProductPurchasesRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCRGUniversityMgtApp.NEPService.ProductService.ProductPurchase[] ProductPurchasesRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductPurchase[] ProductPurchasesRecords {
            get {
                return this.ProductPurchasesRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPurchasesRecordsField, value) != true)) {
                    this.ProductPurchasesRecordsField = value;
                    this.RaisePropertyChanged("ProductPurchasesRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NEPService.ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddProduct", ReplyAction="http://tempuri.org/IProductService/AddProductResponse")]
        int AddProduct(HCRGUniversityMgtApp.NEPService.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddProduct", ReplyAction="http://tempuri.org/IProductService/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(HCRGUniversityMgtApp.NEPService.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        int UpdateProduct(HCRGUniversityMgtApp.NEPService.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        System.Threading.Tasks.Task<int> UpdateProductAsync(HCRGUniversityMgtApp.NEPService.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProduct", ReplyAction="http://tempuri.org/IProductService/DeleteProductResponse")]
        void DeleteProduct(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProduct", ReplyAction="http://tempuri.org/IProductService/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProductByProductName", ReplyAction="http://tempuri.org/IProductService/GetPagedProductByProductNameResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct GetPagedProductByProductName(string productName, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProductByProductName", ReplyAction="http://tempuri.org/IProductService/GetPagedProductByProductNameResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct> GetPagedProductByProductNameAsync(string productName, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductByID", ReplyAction="http://tempuri.org/IProductService/GetProductByIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.Product GetProductByID(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductByID", ReplyAction="http://tempuri.org/IProductService/GetProductByIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.Product> GetProductByIDAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProduct", ReplyAction="http://tempuri.org/IProductService/GetPagedProductResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct GetPagedProduct(int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProduct", ReplyAction="http://tempuri.org/IProductService/GetPagedProductResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct> GetPagedProductAsync(int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProductByProductType", ReplyAction="http://tempuri.org/IProductService/GetPagedProductByProductTypeResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase GetPagedProductByProductType(string productType, int userid, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPagedProductByProductType", ReplyAction="http://tempuri.org/IProductService/GetPagedProductByProductTypeResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase> GetPagedProductByProductTypeAsync(string productType, int userid, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductShoppingAllByProductID", ReplyAction="http://tempuri.org/IProductService/GetProductShoppingAllByProductIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.ProductShopping[] GetProductShoppingAllByProductID(int _productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductShoppingAllByProductID", ReplyAction="http://tempuri.org/IProductService/GetProductShoppingAllByProductIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShopping[]> GetProductShoppingAllByProductIDAsync(int _productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/addProductQuantity", ReplyAction="http://tempuri.org/IProductService/addProductQuantityResponse")]
        int addProductQuantity(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/addProductQuantity", ReplyAction="http://tempuri.org/IProductService/addProductQuantityResponse")]
        System.Threading.Tasks.Task<int> addProductQuantityAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/updateProductQuantity", ReplyAction="http://tempuri.org/IProductService/updateProductQuantityResponse")]
        int updateProductQuantity(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/updateProductQuantity", ReplyAction="http://tempuri.org/IProductService/updateProductQuantityResponse")]
        System.Threading.Tasks.Task<int> updateProductQuantityAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductQuantityByID", ReplyAction="http://tempuri.org/IProductService/getProductQuantityByIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity getProductQuantityByID(int productQuantityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductQuantityByID", ReplyAction="http://tempuri.org/IProductService/getProductQuantityByIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity> getProductQuantityByIDAsync(int productQuantityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductQuantityDetailByProductID", ReplyAction="http://tempuri.org/IProductService/getProductQuantityDetailByProductIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity getProductQuantityDetailByProductID(int productID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductQuantityDetailByProductID", ReplyAction="http://tempuri.org/IProductService/getProductQuantityDetailByProductIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity> getProductQuantityDetailByProductIDAsync(int productID, int skip, int take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductQuantityByProductID", ReplyAction="http://tempuri.org/IProductService/GetProductQuantityByProductIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity GetProductQuantityByProductID(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductQuantityByProductID", ReplyAction="http://tempuri.org/IProductService/GetProductQuantityByProductIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity> GetProductQuantityByProductIDAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/addProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/addProductShippingDetailResponse")]
        int addProductShippingDetail(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/addProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/addProductShippingDetailResponse")]
        System.Threading.Tasks.Task<int> addProductShippingDetailAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/updateProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/updateProductShippingDetailResponse")]
        int updateProductShippingDetail(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/updateProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/updateProductShippingDetailResponse")]
        System.Threading.Tasks.Task<int> updateProductShippingDetailAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductShippingDetailByIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail getProductShippingDetailByID(int _productShippingDetailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductShippingDetailByIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail> getProductShippingDetailByIDAsync(int _productShippingDetailID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/getProductShippingDetailResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductShippingDetail getProductShippingDetail(int _skip, int _take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingDetail", ReplyAction="http://tempuri.org/IProductService/getProductShippingDetailResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductShippingDetail> getProductShippingDetailAsync(int _skip, int _take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingAddressDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductShippingAddressDetailByIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingAddressDetailByID getProductShippingAddressDetailByID(System.Nullable<int> _shippingPaymentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductShippingAddressDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductShippingAddressDetailByIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingAddressDetailByID> getProductShippingAddressDetailByIDAsync(System.Nullable<int> _shippingPaymentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductPurchaseDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductPurchaseDetailByIDResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase getProductPurchaseDetailByID(System.Nullable<int> _shippingPaymentID, int _skip, int _take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductPurchaseDetailByID", ReplyAction="http://tempuri.org/IProductService/getProductPurchaseDetailByIDResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase> getProductPurchaseDetailByIDAsync(System.Nullable<int> _shippingPaymentID, int _skip, int _take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductPurchaseDetail", ReplyAction="http://tempuri.org/IProductService/getProductPurchaseDetailResponse")]
        HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchasesRecord getProductPurchaseDetail(int _skip, int _take, int OrganizationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/getProductPurchaseDetail", ReplyAction="http://tempuri.org/IProductService/getProductPurchaseDetailResponse")]
        System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchasesRecord> getProductPurchaseDetailAsync(int _skip, int _take, int OrganizationID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : HCRGUniversityMgtApp.NEPService.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<HCRGUniversityMgtApp.NEPService.ProductService.IProductService>, HCRGUniversityMgtApp.NEPService.ProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddProduct(HCRGUniversityMgtApp.NEPService.ProductService.Product product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(HCRGUniversityMgtApp.NEPService.ProductService.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public int UpdateProduct(HCRGUniversityMgtApp.NEPService.ProductService.Product product) {
            return base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task<int> UpdateProductAsync(HCRGUniversityMgtApp.NEPService.ProductService.Product product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        public void DeleteProduct(int productID) {
            base.Channel.DeleteProduct(productID);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int productID) {
            return base.Channel.DeleteProductAsync(productID);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct GetPagedProductByProductName(string productName, int skip, int take) {
            return base.Channel.GetPagedProductByProductName(productName, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct> GetPagedProductByProductNameAsync(string productName, int skip, int take) {
            return base.Channel.GetPagedProductByProductNameAsync(productName, skip, take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.Product GetProductByID(int productID) {
            return base.Channel.GetProductByID(productID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.Product> GetProductByIDAsync(int productID) {
            return base.Channel.GetProductByIDAsync(productID);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct GetPagedProduct(int skip, int take) {
            return base.Channel.GetPagedProduct(skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProduct> GetPagedProductAsync(int skip, int take) {
            return base.Channel.GetPagedProductAsync(skip, take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase GetPagedProductByProductType(string productType, int userid, int skip, int take) {
            return base.Channel.GetPagedProductByProductType(productType, userid, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase> GetPagedProductByProductTypeAsync(string productType, int userid, int skip, int take) {
            return base.Channel.GetPagedProductByProductTypeAsync(productType, userid, skip, take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductShopping[] GetProductShoppingAllByProductID(int _productID) {
            return base.Channel.GetProductShoppingAllByProductID(_productID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShopping[]> GetProductShoppingAllByProductIDAsync(int _productID) {
            return base.Channel.GetProductShoppingAllByProductIDAsync(_productID);
        }
        
        public int addProductQuantity(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity) {
            return base.Channel.addProductQuantity(productQuantity);
        }
        
        public System.Threading.Tasks.Task<int> addProductQuantityAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity) {
            return base.Channel.addProductQuantityAsync(productQuantity);
        }
        
        public int updateProductQuantity(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity) {
            return base.Channel.updateProductQuantity(productQuantity);
        }
        
        public System.Threading.Tasks.Task<int> updateProductQuantityAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity productQuantity) {
            return base.Channel.updateProductQuantityAsync(productQuantity);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity getProductQuantityByID(int productQuantityID) {
            return base.Channel.getProductQuantityByID(productQuantityID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductQuantity> getProductQuantityByIDAsync(int productQuantityID) {
            return base.Channel.getProductQuantityByIDAsync(productQuantityID);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity getProductQuantityDetailByProductID(int productID, int skip, int take) {
            return base.Channel.getProductQuantityDetailByProductID(productID, skip, take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity> getProductQuantityDetailByProductIDAsync(int productID, int skip, int take) {
            return base.Channel.getProductQuantityDetailByProductIDAsync(productID, skip, take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity GetProductQuantityByProductID(int productID) {
            return base.Channel.GetProductQuantityByProductID(productID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductQuantity> GetProductQuantityByProductIDAsync(int productID) {
            return base.Channel.GetProductQuantityByProductIDAsync(productID);
        }
        
        public int addProductShippingDetail(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail) {
            return base.Channel.addProductShippingDetail(productShippingDetail);
        }
        
        public System.Threading.Tasks.Task<int> addProductShippingDetailAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail) {
            return base.Channel.addProductShippingDetailAsync(productShippingDetail);
        }
        
        public int updateProductShippingDetail(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail) {
            return base.Channel.updateProductShippingDetail(productShippingDetail);
        }
        
        public System.Threading.Tasks.Task<int> updateProductShippingDetailAsync(HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail productShippingDetail) {
            return base.Channel.updateProductShippingDetailAsync(productShippingDetail);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail getProductShippingDetailByID(int _productShippingDetailID) {
            return base.Channel.getProductShippingDetailByID(_productShippingDetailID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingDetail> getProductShippingDetailByIDAsync(int _productShippingDetailID) {
            return base.Channel.getProductShippingDetailByIDAsync(_productShippingDetailID);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductShippingDetail getProductShippingDetail(int _skip, int _take) {
            return base.Channel.getProductShippingDetail(_skip, _take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductShippingDetail> getProductShippingDetailAsync(int _skip, int _take) {
            return base.Channel.getProductShippingDetailAsync(_skip, _take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingAddressDetailByID getProductShippingAddressDetailByID(System.Nullable<int> _shippingPaymentID) {
            return base.Channel.getProductShippingAddressDetailByID(_shippingPaymentID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.ProductShippingAddressDetailByID> getProductShippingAddressDetailByIDAsync(System.Nullable<int> _shippingPaymentID) {
            return base.Channel.getProductShippingAddressDetailByIDAsync(_shippingPaymentID);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase getProductPurchaseDetailByID(System.Nullable<int> _shippingPaymentID, int _skip, int _take) {
            return base.Channel.getProductPurchaseDetailByID(_shippingPaymentID, _skip, _take);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchase> getProductPurchaseDetailByIDAsync(System.Nullable<int> _shippingPaymentID, int _skip, int _take) {
            return base.Channel.getProductPurchaseDetailByIDAsync(_shippingPaymentID, _skip, _take);
        }
        
        public HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchasesRecord getProductPurchaseDetail(int _skip, int _take, int OrganizationID) {
            return base.Channel.getProductPurchaseDetail(_skip, _take, OrganizationID);
        }
        
        public System.Threading.Tasks.Task<HCRGUniversityMgtApp.NEPService.ProductService.PagedProductPurchasesRecord> getProductPurchaseDetailAsync(int _skip, int _take, int OrganizationID) {
            return base.Channel.getProductPurchaseDetailAsync(_skip, _take, OrganizationID);
        }
    }
}
